### ISSUE TITLE
keyword where is not highlighted

### ISSUE THREAD

**Issue by doongjohn** [ap29600/tree-sitter-odin#1]
```odin
say_hello :: proc(person: $T)
	where intrinsics.type_field_type(T, "name") == string {
	fmt.printf("Hello, {}!\n", person.name)
}
```

**Comment by ap29600** [comment]
Should be fixed in the latest merge

**Comment by doongjohn** [comment]
thanks for the update!

however I thought I was using tree-sitter for the syntax highlight but I wasn't xD

so I disabled the regex highlighting and found out that this parser is not working

![image](https://user-images.githubusercontent.com/40219740/181592916-1e9b018d-b6b6-4be8-88f6-8fbea568ab72.png)

any idea why this is not working?

**Comment by ap29600** [comment]
what does your neovim config look like? I have this snippet in there:
```lua
local parser_config = require "nvim-treesitter.parsers".get_parser_configs()
parser_config.odin = {
  install_info = {
    url = "~/sources/tree-sitter-odin", -- local path or git repo
    files = {"src/parser.c"}
  },
  filetype = "odin", -- if filetype does not agree with parser name
  used_by = {} -- additional filetypes that use this parser
}
```
and symlink the queries folder in the github repo to `<your_vim_config_location>/queries/odin`

I am not 100% sure this is the correct way to do this, but it worked for me.

**Comment by doongjohn** [comment]
thanks a lot! now it works
